/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@stencil/redux';


export namespace Components {

  interface DrizzleApp {}
  interface DrizzleAppAttributes extends StencilHTMLAttributes {}

  interface DrzData {}
  interface DrzDataAttributes extends StencilHTMLAttributes {}

  interface MyTodo {
    'id': string;
    'value': string;
  }
  interface MyTodoAttributes extends StencilHTMLAttributes {
    'id'?: string;
    'onRemoveTodo'?: (event: CustomEvent) => void;
    'onUpdateTodo'?: (event: CustomEvent) => void;
    'value'?: string;
  }

  interface TodoList {}
  interface TodoListAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'DrizzleApp': Components.DrizzleApp;
    'DrzData': Components.DrzData;
    'MyTodo': Components.MyTodo;
    'TodoList': Components.TodoList;
  }

  interface StencilIntrinsicElements {
    'drizzle-app': Components.DrizzleAppAttributes;
    'drz-data': Components.DrzDataAttributes;
    'my-todo': Components.MyTodoAttributes;
    'todo-list': Components.TodoListAttributes;
  }


  interface HTMLDrizzleAppElement extends Components.DrizzleApp, HTMLStencilElement {}
  var HTMLDrizzleAppElement: {
    prototype: HTMLDrizzleAppElement;
    new (): HTMLDrizzleAppElement;
  };

  interface HTMLDrzDataElement extends Components.DrzData, HTMLStencilElement {}
  var HTMLDrzDataElement: {
    prototype: HTMLDrzDataElement;
    new (): HTMLDrzDataElement;
  };

  interface HTMLMyTodoElement extends Components.MyTodo, HTMLStencilElement {}
  var HTMLMyTodoElement: {
    prototype: HTMLMyTodoElement;
    new (): HTMLMyTodoElement;
  };

  interface HTMLTodoListElement extends Components.TodoList, HTMLStencilElement {}
  var HTMLTodoListElement: {
    prototype: HTMLTodoListElement;
    new (): HTMLTodoListElement;
  };

  interface HTMLElementTagNameMap {
    'drizzle-app': HTMLDrizzleAppElement
    'drz-data': HTMLDrzDataElement
    'my-todo': HTMLMyTodoElement
    'todo-list': HTMLTodoListElement
  }

  interface ElementTagNameMap {
    'drizzle-app': HTMLDrizzleAppElement;
    'drz-data': HTMLDrzDataElement;
    'my-todo': HTMLMyTodoElement;
    'todo-list': HTMLTodoListElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
